version: "3.8"

services:
  db:
    image: mysql:8
    container_name: moeda_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_moeda_estudantil
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [app-net]

  backend:
    build: ./backend
    container_name: moeda_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: sistema_moeda_estudantil
      NODE_ENV: production
    ports:
      - "3001:3001"
    networks: [app-net]

  frontend:
    build: ./frontend
    container_name: moeda_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3001
      HOST: 0.0.0.0
      PORT: 5173
    ports:
      - "5173:5173"
    networks: [app-net]

networks:
  app-net:
    driver: bridge
